# -*- coding: utf-8 -*-
"""assistente_virtual.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dCFtQasiL631LPNXgSHKfyWH_41oFL3K
"""

!pip3 install pyautogui
!sudo apt install build-essential portaudio19-dev
!pip3 install SpeechRecognition
!pip3 install pyttsx3
!pip3 install wikipedia
!pip3 install pywhatkit
!pip3 install PyAudio

import speech_recognition as sr
import pyttsx3
import datetime
import wikipedia
#import pywhatkit
import sys
import time

for index, name in enumerate(sr.Microphone.list_microphone_names()):
    print("Microphone with name \"{1}\" found for `Microphone(device_index={0})`".format(index, name))

audio = sr.Recognizer()
#maquina = pyttsx3.init()

def executa_comando():
    try:
        with sr.Microphone() as source:
            print('Ouvindo...')
            voz = audio.listen(source, 5)
            comando = audio.recognize_google(voz, language='pt-BR')
            if not isinstance(comando, str):
                return False
            comando = comando.lower()
            print(comando)
            if 'ana' in comando:
                comando = comando.split('ana ', 1)[1]
                if comando is not None:
                    return comando

    except:
        sys.exit('Microfone não identificado')

def comando_voz_usuario():
    comando = executa_comando()
    if not comando:
        print('Algo deu errado, tente de novo')
        return False
    #maquina.say('Te escutei, processando')
    #maquina.runAndWait()
    if 'encerrar' in comando:
        #maquina.say('Tchau, até breve!')
        #maquina.runAndWait()
        return True
    elif 'calcular' in comando:
        calcular = comando.replace('calcular', '')
        resultado = eval(calcular)
        print(resultado)
        #maquina.say('O resultado é '+str(resultado))
        #maquina.runAndWait()
    elif 'horas' in comando:
        hora = datetime.datetime.now().strftime('%H:%M')
        #maquina.say('Agora são' + hora)
        #maquina.runAndWait()
    elif 'procure por' in comando:
        procurar = comando.replace('procure por', '')
        wikipedia.set_lang('pt')
        resultado = wikipedia.summary(procurar,2)
        print('Resultado: '+resultado)
        #maquina.say(resultado)
        #maquina.runAndWait()
    '''elif 'tocar' in comando:
        musica = comando.replace('tocar','')
        resultado = pywhatkit.playonyt(musica)
        maquina.say('Tocando música')
        maquina.runAndWait()'''
    return False

while True:
    if comando_voz_usuario():
        break;
print("Fim")
